# Site settings
title: SNY Blog
SEOTitle: ç´¢å°¼å¨…çš„åšå®¢ | SNY Blog
header-img: img/post-bg-desk.jpg
email: 550906133@qq.com
description: "ä¹Ÿæ¸©æŸ”ï¼Œä¹Ÿè‹±å‹‡"
keyword: "SNY, SNY Blog, ç´¢å°¼å¨…çš„åšå®¢, suoniya, liuruining"
# url: "http://suoniya.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
# github_repo: "https://github.com/suoniya/suoniya.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "å¯èƒ½æ˜¯æœ‰å²ä»¥æ¥æœ€ç©ºçš„åšå®¢äº†ï¼Œå› ä¸ºæˆ‘å‹æ ¹å°±ä¸ä¼šä½¿ç”¨ğŸ¤£!"
sidebar-avatar: /img/about_liuruining.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     
zhihu_username:    
github_username:    suoniya
facebook_username:  
jianshu_username:   
#twitter_username:  




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# è¯„è®ºç³»ç»Ÿ
# Disqusï¼ˆhttps://disqus.com/ï¼‰
# disqus_username: suoniya

# Gitalk
gitalk:
  enable: true    #æ˜¯å¦å¼€å¯Gitalkè¯„è®º
  clientID: 5565a1bcc8b244e5a25a                            #ç”Ÿæˆçš„clientID
  clientSecret: 48c273dd70c02b1a9a67358584e710c53e17073b    #ç”Ÿæˆçš„clientSecret
  repo: suoniya.github.io    #ä»“åº“åç§°
  owner: suoniya    #githubç”¨æˆ·å
  admin: suoniya
  id: md5(location.href)
  distractionFreeMode: false #æ˜¯å¦å¯ç”¨ç±»ä¼¼FBçš„é˜´å½±é®ç½©


# ç»Ÿè®¡

# Analytics settings
# Baidu Analytics
# ba_track_id: 

# Google Analytics
# ga_track_id:            # Format: UA-xxxxxx-xx
# ga_domain: auto               # é»˜è®¤çš„æ˜¯ auto, è¿™é‡Œæˆ‘æ˜¯è‡ªå®šä¹‰äº†çš„åŸŸåï¼Œä½ å¦‚æœæ²¡æœ‰è‡ªå·±çš„åŸŸåï¼Œéœ€è¦æ”¹æˆauto





# Featured Tags
featured-tags: true                     # æ˜¯å¦ä½¿ç”¨é¦–é¡µæ ‡ç­¾
featured-condition-size: 1              # ç›¸åŒæ ‡ç­¾æ•°é‡å¤§äºè¿™ä¸ªæ•°ï¼Œæ‰ä¼šå‡ºç°åœ¨é¦–é¡µ



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "",
        href: ""
    },{
        title: "",
        href: ""
    },{
        title: "",
        href: ""
    },{
        title: "",
        href: ""
    }
]
